export default {
  GET_ORDERS_INIT: "GET_ORDERS_INIT",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_PAGINATED: "GET_ORDERS_PAGINATED",

  UPDATE_ORDER_STATUS_INIT: "UPDATE_ORDER_STATUS_INIT",
  UPDATE_ORDER_STATUS_SUCCESS: "UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_FAILURE: "UPDATE_ORDER_STATUS_FAILURE",

  GET_PRODUCT_PRICES_INIT: 'GET_PRODUCT_PRICES_INIT',
  GET_PRODUCT_PRICES_SUCCESS: 'GET_PRODUCT_PRICES_SUCCESS ',

  ORDER_STATUS: [
    'ORDERED',
    'PRE-PAYMENT',
    'PAID',
    'SHIPPED',
    'DELIVERED'
  ]
}