export default {
  GET_PRODUCTS_INIT: "GET_PRODUCTS_INIT",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",

  GET_PRODUCT_PRICES_INIT: "GET_PRODUCT_PRICES_INIT",
  GET_PRODUCT_PRICES_SUCCESS: "GET_PRODUCT_PRICES_SUCCESS",

  GET_COUNTRIES_INIT: "GET_COUNTRIES_INIT",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS"
}